# Generated by Django 3.2 on 2021-12-16 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_category_v'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='V',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
