# Generated by Django 3.2 on 2022-01-17 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_category_creation_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
