# Generated by Django 3.2 on 2021-12-18 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='BaghdadiName',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
