# Generated by Django 3.2 on 2021-12-18 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0002_user_baghdadiname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='BaghdadiName',
        ),
    ]
