# Generated by Django 3.2 on 2021-12-18 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providerdocuments',
            name='provider',
        ),
        migrations.DeleteModel(
            name='Provider',
        ),
        migrations.DeleteModel(
            name='ProviderDocuments',
        ),
    ]
