# Generated by Django 3.2 on 2021-12-18 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provider',
            options={'ordering': ['user__first_name', 'user__last_name']},
        ),
        migrations.RemoveField(
            model_name='provider',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='provider',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('B', 'Blocked'), ('V', 'Verified')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='provider',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='authenticator.user'),
            preserve_default=False,
        ),
    ]
