# Generated by Django 4.0.3 on 2022-06-11 21:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudienceRateMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='EnrolledToMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('brief_description', models.CharField(max_length=1255)),
                ('text', models.CharField(max_length=2555)),
                ('video', models.URLField()),
                ('duration', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1255, null=True)),
                ('brief_description', models.CharField(max_length=1255, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('last_update', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('Pr', 'Private'), ('Pu', 'Public')], default='Private', max_length=255)),
                ('requirements', models.CharField(max_length=1255, null=True)),
                ('what_will_learn', models.CharField(max_length=1255)),
                ('duration', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(12000)])),
                ('is_blocked', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category_manager.category')),
            ],
        ),
    ]
