# Generated by Django 4.0.3 on 2022-06-11 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('material_manager', '0001_initial'),
        ('users_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_manager.provider'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material_manager.material'),
        ),
        migrations.AddField(
            model_name='enrolledtomaterial',
            name='audience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_manager.audience'),
        ),
        migrations.AddField(
            model_name='enrolledtomaterial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material_manager.material'),
        ),
        migrations.AddField(
            model_name='audienceratematerial',
            name='audience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_manager.audience'),
        ),
        migrations.AddField(
            model_name='audienceratematerial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material_manager.material'),
        ),
        migrations.AlterUniqueTogether(
            name='enrolledtomaterial',
            unique_together={('material', 'audience')},
        ),
    ]
