# Generated by Django 3.2 on 2022-01-02 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0006_material_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='instructor',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='likes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
