# Generated by Django 4.0.3 on 2022-03-30 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('_platform', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='material',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_platform.category'),
        ),
        migrations.AddField(
            model_name='material',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_platform.provider'),
        ),
        migrations.AddField(
            model_name='content',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='_platform.document'),
        ),
        migrations.AddField(
            model_name='content',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_platform.material'),
        ),
    ]
