# Generated by Django 4.0.3 on 2022-03-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_platform', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='the_status',
        ),
        migrations.AddField(
            model_name='material',
            name='last_update',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='material',
            name='status',
            field=models.CharField(choices=[('Pr', 'Private'), ('Pu', 'Public')], default='Pr', max_length=255),
        ),
    ]
