# Generated by Django 4.0.3 on 2022-05-10 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('_platform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='material',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_platform.category'),
        ),
        migrations.AddField(
            model_name='material',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_platform.provider'),
        ),
        migrations.AddField(
            model_name='enrolledtomaterial',
            name='audience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_platform.audience'),
        ),
        migrations.AddField(
            model_name='enrolledtomaterial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_platform.material'),
        ),
        migrations.AddField(
            model_name='document',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_platform.content'),
        ),
        migrations.AddField(
            model_name='content',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_platform.material'),
        ),
        migrations.AddField(
            model_name='audience',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='enrolledtomaterial',
            unique_together={('material', 'audience')},
        ),
    ]
