# Generated by Django 4.0.3 on 2022-05-23 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_platform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='duration',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='material',
            name='duration',
            field=models.CharField(max_length=10),
        ),
    ]
