# Generated by Django 4.0.3 on 2022-05-24 17:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_platform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='duration',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(12000)]),
        ),
    ]
