# Generated by Django 4.0.3 on 2022-03-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_platform', '0002_remove_material_the_status_material_last_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='requirements',
            field=models.CharField(max_length=1255, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='what_will_learn',
            field=models.CharField(default=1, max_length=1255),
            preserve_default=False,
        ),
    ]
