# Generated by Django 4.0.3 on 2022-05-07 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_platform', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provider',
            options={'ordering': ['user__first_name']},
        ),
        migrations.RemoveField(
            model_name='provider',
            name='major',
        ),
        migrations.AddField(
            model_name='provider',
            name='description',
            field=models.CharField(default=1, max_length=1255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider',
            name='pic',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
