# Generated by Django 4.0.3 on 2022-05-23 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('_platform', '0002_alter_lecture_duration_alter_material_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudienceRateMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.BooleanField()),
                ('audience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_platform.audience')),
            ],
        ),
    ]
