# Generated by Django 4.0.3 on 2022-05-25 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_platform', '0002_alter_material_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='content',
            new_name='lecture',
        ),
    ]
