# Generated by Django 4.0.3 on 2022-05-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_platform', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provider',
            options={'ordering': ['user__first_name'], 'permissions': [('block_provider', 'Can block a provider'), ('unblock_provider', 'Can unblock a provider'), ('verify_provider', 'Can verify a provider')]},
        ),
        migrations.AlterField(
            model_name='provider',
            name='description',
            field=models.CharField(max_length=1255, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
