# Generated by Django 4.0.3 on 2022-05-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_platform', '0003_rename_content_document_lecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='major',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
