# Generated by Django 4.0.3 on 2022-03-15 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_platform', '0003_material_provider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provider',
            options={'ordering': ['user__first_name', 'major'], 'permissions': [('block provider', 'Can block a provider')]},
        ),
    ]
