# Generated by Django 4.0.3 on 2022-05-23 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('_platform', '0003_audienceratematerial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audienceratematerial',
            name='material',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='_platform.material'),
            preserve_default=False,
        ),
    ]
