# Generated by Django 4.0.3 on 2022-03-24 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('_platform', '0003_material_requirements_material_what_will_learn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='material',
            name='status',
            field=models.CharField(choices=[('Pr', 'Private'), ('Pu', 'Public')], default='Private', max_length=255),
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('brief_description', models.CharField(max_length=1255)),
                ('content', models.CharField(max_length=2555)),
                ('video', models.FileField(upload_to='')),
                ('order', models.PositiveIntegerField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_platform.document')),
            ],
            options={
                'unique_together': {('id', 'order')},
            },
        ),
    ]
