# Generated by Django 4.0.3 on 2022-05-15 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_platform', '0003_alter_provider_options_alter_provider_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provider',
            options={},
        ),
    ]
