# Generated by Django 4.0.3 on 2022-03-15 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_platform', '0004_alter_provider_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provider',
            options={'ordering': ['user__first_name', 'major'], 'permissions': [('block_provider', 'Can block a provider'), ('unblock_provider', 'Can unblock a provider'), ('verify_provider', 'Can verify a provider')]},
        ),
    ]
