# Generated by Django 4.0.3 on 2022-03-24 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_platform', '0004_document_alter_material_status_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='material',
            field=models.ManyToManyField(to='_platform.material'),
        ),
    ]
