# Generated by Django 4.0.3 on 2022-05-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_platform', '0004_audienceratematerial_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
