# Generated by Django 4.0.3 on 2022-05-22 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_platform', '0004_alter_provider_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Content',
            new_name='Lecture',
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
