# Generated by Django 4.0.3 on 2022-05-08 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('_platform', '0004_audience'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrolledToMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_platform.audience')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_platform.material')),
            ],
            options={
                'unique_together': {('material', 'audience')},
            },
        ),
    ]
