# Generated by Django 4.0.3 on 2022-05-23 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_platform', '0005_rename_content_lecture_alter_category_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='order',
        ),
        migrations.AlterField(
            model_name='lecture',
            name='video',
            field=models.URLField(),
        ),
    ]
