# Generated by Django 4.0.3 on 2022-03-24 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('_platform', '0005_content_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='material',
        ),
        migrations.AddField(
            model_name='content',
            name='material',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='_platform.material'),
            preserve_default=False,
        ),
    ]
