# Generated by Django 4.0.3 on 2022-03-24 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('_platform', '0006_remove_content_material_content_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='_platform.document'),
        ),
    ]
