# Generated by Django 4.0.3 on 2022-03-24 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_platform', '0007_alter_content_document'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='content',
            unique_together={('material', 'order')},
        ),
    ]
