# Generated by Django 4.0.3 on 2022-03-24 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_platform', '0008_alter_content_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='content',
            unique_together=set(),
        ),
    ]
