# Generated by Django 4.0.3 on 2022-03-15 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('_platform', '0002_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='_platform.provider'),
            preserve_default=False,
        ),
    ]
