# Generated by Django 4.0.3 on 2022-03-12 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_platform', '0003_audience_user_provider_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provider',
            options={'ordering': ['user__first_name']},
        ),
    ]
